### PR TITLE
28 stylying pages sign up

### LINKED ISSUE #28: styling pages
as I user
so that I can get a lot of viewers and rent my space
I want nice looking pages for AirBnb website

Added as we will need to style it up pages, it can be divided into different user stories to address specific pages.

### PR DESCRIPTION
**Pull request by SergioETrillo**
Closes #28 
a bit of styling for sign-up and sign-in

Agreed, other things will probably need to be added, but it is so nice to send Pull requests.

Aday has done the donkey work on this one, well done!

### CODE REVIEW

**Comment by missamynicholson** [comment]
The signup and login pages look SO much better and make it much easier when testing - well done guys!

I don't have any corrections....just a question.
In the style.css file there are a few things in there that I can't find in the main code, mainly related to radio buttons. Is there some fancy bootstrap stuff going on with radio buttons?
**Please select your answer:** 
Yes 🔘 
No  🔘 

[Also, we just need to write ourselves a note to have a look at how we require the public folder. I couldn't get the Proc thing to work that they suggested in the Chitter rubric. The only way I could get it to work is `set :public, "public"` but I suspect this is bad practice as it keeps throwing up a warning in my Terminal.]

But otherwise....good job! 👍

**Comment by SergioETrillo** [comment]
hi Amy,

Thank you for your thorough review.  Very useful, even if I saw it a bit late.
- Radio buttons: I have removed those now, (even without reading your comments first, my hidden sense of "you are going to get into trouble" warned me... :smile: 
- public folder: I would suggest that we stick to the line:
  `set :public_folder, "public"`  that is in the master right now.  using "public" only gives a warning and made Aday and myself unhappy for almost an hour, and we stop trying to fix it in desperation.  Then I got the happy idea of _reading_ what the warning message said and follow its instructions, and it was fixed, (I know, very radical)

It seems that there are some merging issues on this one too, I suspect there will be the same small things that we had today, as this PR is slightly older.  Hopefully we will be able to merge quicker than today!

**_**EDIT_\* _: the merging issues were in the style.css, I was able to fix them and leave you with the PR ready to merge._

**Comment by SergioETrillo** [comment]
The merging conflict was in the public/style.css file.  As a courtesy I have just removed the conflicts and let you the PR ready to merge.  :zzz:

**Comment by missamynicholson** [comment]
:shipit:

It's starting to look pretty snazzy! 😎 

Excellent work on the merge conflicts 💯

**Pull request merged**
